# To change this template, choose Tools | Templates
# and open the template in the editor.

#Property Code is REPORT_PATH
#add \\ at the end of the file path example {D:\\GIT\\PTS_NEW\\ReadingFiles\\ProcessFiles\\}
REPORT_DIRECTORY_WINDOWS=D:\\GIT\\PTS_NEW\\ReadingFiles\\ProcessFiles\\Reports\\
REPORT_DIRECTORY_LINUX=/../home/MVMMS

#Property Code is EXPORT_REPORT_PATH
#add \\ at the end of the file path example {D:\\GIT\\PTS_NEW\\ReadingFiles\\ProcessFiles\\}
EXPORT_REPORT_DIRECTORY_WINDOWS=D:/iReportsOut/
EXPORT_REPORT_DIRECTORY_LINUX=/../home/iReportsOut/

#Property Code is FILE_PATH
#add \\ at the end of the file path example {D:\\GIT\\PTS_NEW\\ReadingFiles\\ProcessFiles\\}
READING_FILE_DIRECTORY_WINDOWS=D:\\GIT\\PTS_NEW\\ReadingFiles\\ProcessFiles\\
READING_FILE_DIRECTORY_LINUX=/../home/MVMMS


mongodb.url=1.2.3.4
mongodb.db=hello

db.driverClassName=com.mysql.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/netjs
db.username=root
db.password=password
pool.initialSize=5


